plugins:
  - path: .yarn/plugins/@ojkelly/plugin-package-yaml.cjs
    spec: "https://yarn.build/yaml"
  - path: .yarn/plugins/@ojkelly/plugin-visualize.cjs
  - path: .yarn/plugins/@ojkelly/plugin-all.cjs
    spec: "https://yarn.build/latest"

